#!/bin/sh
# простой init для отладки
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev || true

# создать узлы, если их нет
[ -e /dev/console ] || mknod /dev/console c 5 1
[ -e /dev/null ] || mknod /dev/null c 1 3

echo "initramfs: starting shell"
exec /bin/sh
